---
title: "Data624 Project 1"
author: "Esteban Aramayo, Coffy Andrews-Guo, LeTicia Cancel, Joseph Connolly, Ian Costello"
date: '2022-06-13'
output: 
  word_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
---

```{r warning=FALSE}
#libraries
library(readxl)
```




```{r}
df <- read_excel("data.xls")
head(df)
```

## Data Exploration

```{r}
summary(df)
```
Boxplots: Var02 has the most outliers
```{r warning=FALSE, fig.width=10, fig.height=8}
p1 <- ggplot(df, aes(category, Var01)) +
  geom_boxplot()
p2 <- ggplot(df, aes(category, Var02)) +
  geom_boxplot()
p3 <- ggplot(df, aes(category, Var03)) +
  geom_boxplot()
p4 <- ggplot(df, aes(category, Var05)) +
  geom_boxplot()
p5 <- ggplot(df, aes(category, Var07)) +
  geom_boxplot()

p1+p2+p3+p4+p5+
  plot_layout(ncol = 3)
```

All predictors are left skewed so transformations are needed for each column
```{r warning=FALSE, fig.width=10, fig.height=7}
p1 <- ggplot(df, aes(Var01, color=category)) +
  geom_density()
p2 <- ggplot(df, aes(Var02, color=category)) +
  geom_density()
p3 <- ggplot(df, aes(Var03, color=category)) +
  geom_density()
p4 <- ggplot(df, aes(Var05, color=category)) +
  geom_density()
p5 <- ggplot(df, aes(Var07, color=category)) +
  geom_density()

p1+p2+p3+p4+p5+
  plot_layout(ncol = 2)
```

The NAs make up less than 10% of all values in the data. 
```{r}
aggr(df, col=c('navyblue','yellow'),
     numbers=TRUE, sortVars=TRUE,
     labels=names(df), cex.axis=.7,
     gap=3, ylab=c("Missing data","Pattern"))
```
## Data transformations

```{r}

```











